config/routes.rb
Rails.application.routes.draw do
  # get 'requests/show'
  # get 'requests/create'
  # get 'requests/new'
  # get 'requests/destroy'
  # get 'animals/index'
  # get 'animals/show'
  devise_for :users
  root to: "pages#home"
  get "/find-animals", to: "pages#find_animals"
  # get "/dashboard", to: "pages#dashboard"
  #post "requests", to: "requests#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :animals, only: [:show, :index] do
    resources :requests, only: [:create, :new]
  end
  resources :requests, only: [:destroy , :index, :show] do
    resources :messages, only: :create
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :shelter
  has_many :requests, dependent: :destroy
  has_one_attached :photo

  def score(user_input)
    score = 20

    if user_input[:gender].present? && self.gender == user_input[:gender]
      score += 20
    end
    if user_input[:age].present? && self.age == user_input[:age]
      score += 20
    end
    if user_input[:size].present? && self.size == user_input[:size]
      score += 20
    end
    if user_input[:remote].present? && self.remote == true
      score += 20
    end

    score
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :request
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :animal
  has_many :messages
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  has_many :animals, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :requests
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  #Go trough all animals seeds and compare the category field,and..
  #drop elements that do not match user choice.
  # the every remaining Animal element get score +20
  def index
    if params[:category].present?
      @animals = Animal.where(category: params[:category]).limit(7)
      @animals = @animals.sort_by do |animal|
        # negative score since we want to sort by highest score
        -animal.score(params)
      end
    else
      @animals = Animal.all
    end
  end


  def show
    @animal = Animal.find(params[:id])
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user
    @animal.save
    # No need for app/views/restaurants/create.html.erb
    redirect_to animal_path(@animal)
  end

  def edit
    @animal = Animal.find(params[:id])
  end
  def update
    @animal = Animal.find(params[:id])
    @animal.update(animal_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to animal_path(@animal)
  end

  def destroy
    @animal = Animal.find(params[:id])
    @dress.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to animal_path, status: :see_other
  end

  private

  def animal_params
    params.require(:animal).permit(:category, :gender, :name, :animal_bio, :age,:size, remote:)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["www.fourpaws.lol"] || "localhost:3000" }
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @request = Request.find(params[:request_id])
    @message = Message.new(message_params)
    @message.request = @request
    @message.user = current_user
    if @message.save
      RequestChannel.broadcast_to(
        @request,
        render_to_string(partial: "message", locals: {message: @message})
      )
      head :ok
    else
      render "requests/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  skip_before_action :authenticate_user!, only: :find_animals

  def home
  end

  def find_animals
  end

  def dashboard
    @requests = current_user.requests
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_animal, only: [:create, :edit, :destroy, :update, :new]

  def index
    @requests = Request.all
  end

  def show
    @request = Request.find(params[:id])
    @message = Message.new
  end
  def edit
    @request = Request.find(params[:id])
  end
  def update
    @request = Requests.find(params[:id])
    @request.update(request_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to request_path(@request)
  end

  def create
    puts "new request"
    @request = Request.new(request_params)
    @request.status = "pending"
    @request.animal = @animal
    @request.user = current_user
    if @request.save
      redirect_to requests_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    # We need @request in our `simple_form_for`
    @request = Request.new
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to requests_path, status: :see_other
  end

  private

  def set_animal
    @animal = Animal.find(params[:animal_id])
  end
  def request_params
    params.require(:request).permit(:date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'Fourpaws',
      title: 'Fourpaws',
      reverse: true,
      separator: '|',
      description: 'Adopt, do not shop!',
      keywords: 'animals, organize, lifestyle',
      canonical: request.original_url,
      noindex: !Rails.env.production?,
      icon: [
        { href: image_url('fackbook_cat.png'), rel: 'touch-icon', type: 'image/png' },
      ],
      og: {
        site_name: 'Fourpaws',
        title: 'Fourpaws',
        description: 'Adopt, do not shop!',
        type: 'website',
        url: request.original_url,
        image: image_url('facebook_cat.png')
      }
    }
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    meta_image.starts_with?("http") ? meta_image : image_url("facebook_cat.png")
  end
end

app/views/animals/index.html.erb
<div class="background-2">
<div class ="container" >
<div class="animal-cards">
    <% @animals.each do |animal|%>
      <div class="cardos">
      <% if animal.photo.attached? %>
       <%= cl_image_tag animal.photo.key, height: 300, width: 200, crop: :fill %>
       <% else %>
       <%= image_tag "not_found.png", height: 300, width: 200, crop: :fill%>
       <% end %>
        <div class="card-content">
          <div class="card-text">
            <h3 class="choose-button"><%= link_to "#{animal.name}".capitalize, animal_path(animal), class: "no-decoration" %></h3>
          </div>
        </div>
         <p> <i class="<%='fas fa-heart' if params[:category].present?%>"></i>  <%=animal.score(params)  if params[:category].present? %></p>
        <p><i class="fa-solid fa-hourglass-start"></i>    <%=animal.age%></p>
        <p><i class="fa-solid fa-compress"></i> <%=animal.size%></p>
        <p><i class="fa-solid fa-mars-and-venus"></i></i>  <%= animal.gender.capitalize%></p>
      </div>
    <%end%>

     <% if params[:category].present? %>
     <div class="cardos">

       <%= image_tag "Paw_card.jpg", height: 310, width: 200, crop: :fill%>

        <div class="card-content">
          <div class="card-text">
            <h3 class="choose-button">🤍<%= link_to "See more pets", animals_path, class: "no-decoration"%></h3>
          </div>
        </div>
         <p>Not what <br> you <br> were looking for?<br>click here <br> for more.</p>



      </div>
      <% end %>
</div>
</div>

app/views/animals/show.html.erb
<div class="pet-show">
  <div class="row justify-content-center">
    <div class="col-5">

      <div class="pet-card">
        <div class="pet-banner">
          <% if @animal.photo.attached? %>
      <%= cl_image_tag @animal.photo.key, class: "avatar-large", alt: "avatar-large" %>
       <% else %>
       <%= image_tag "not_found.png", class: "avatar-large", alt: "avatar-large"%>
       <% end %>
       </div>
          <div class="pet-menu">
              <div class="opener"></div>
          </div>
          <h2 class="name"><%= @animal.name.capitalize%></h2>
          <div class="title">"The goodest pet"</div>
          <div class="actions">
              <div class="follow-btn"><button>Back</button></div>

              <div class="follow-btn"><button><%= link_to "Adopt", new_animal_request_path(@animal), class: "follow-btn" %></button></div>
          </div>
          <div class="desc overflow-auto"><%=@animal.animal_bio%></p></div>
      </div>
    </div>

   <div class="col-5">
    <div class="pet-card">
        <div class="pet-banner">
        <% if @animal.photo.attached? %>
      <%= image_tag 'tierheim_logo.png', class: "avatar-large", alt: "avatar-large" %>
       <% else %>
       <%= image_tag "not_found.png", class: "avatar-large", alt: "avatar-large"%>
       <% end %>
            </div>
        <div class="pet-menu">
            <div class="opener"><span></span><span></span><span></span></div>
        </div>
        <h2 class="name">Tierheim München</h2>
        <div class="title">Riemer Str. 270 · 81829 München</div>

        <div class="desc-shelter desc overflow-auto"> <p>The Tierheim München e.V. has been advocating for animals in Munich and the surrounding area for over 180 years, always bearing in mind the maxim "For animals, For people, For Munich." Because nearly every animal's fate is also related to a human one, we do not view animal preservation as a responsibility that is independent of people. Therefore, helping animals is constantly helping people.</p></div>
    </div>
  </div>`
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content= "<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">
  <!-- app/views/layouts/application.html.erb -->
    <%= favicon_link_tag %>
    <title>Fourpaws - Adopt, don't shop!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
<%= render "shared/footer" %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="chatbox" id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.email %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/pages/find_animals.html.erb
<div class="background-1">
  <div class="d-flex justify-content-center">
    <%= form_with url: animals_path, method: :get, class: "find-animals-form" do |f|%>
    <h1 class="header-1"><strong>Let's find your perfect match!</strong></h1>
    <br>
    <div class="row">
      <div class="col-md-12">
        <div>
        <%= label_tag 'Which type of animal do you favor?' %> <br>
        <br>
        <div class="PillListo-item">
           <label>
              <input type="checkbox" name="category" id="category" value="dog">
                <span class="PillListo-label" style="font-size: 2em; color: #1EDD88;"><i class="fa-solid fa-dog fa-xl fa-beat" style="--fa-animation-duration: 2s;"></i>
                <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                </span>
           </label>
        </div>
      </div>
      <div>
        <div class="PillListo-item">
           <label>
              <input type="checkbox" name="category" id="category" value="cat">
                <span class="PillListo-label" style="font-size: 2em; color: #1EDD88;"><i class="fa-solid fa-cat fa-xl fa-beat" style="--fa-animation-duration: 2s;"></i>
                <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                </span>
           </label>
        </div>
      </div>
      </div>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="col-md-12">
        <div>
        <%= label_tag 'Which gender would you prefer?' %> <br>
        <br>
        <div class="PillList-item">
           <label>
              <input type="checkbox" name="gender" id="gender" value="girl">
                <span class="PillList-label"><i class="fa-solid fa-person-dress fa-2xl"></i>
                <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                </span>
           </label>
        </div>
      </div>
      <div>
        <div class="PillListb-item">
           <label>
              <input type="checkbox" name="gender" id="gender" value="boy">
                <span class="PillListb-label"><i class="fa-solid fa-person fa-2xl" style="color: #519fd3"></i>
                <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                </span>
           </label>
        </div>
      </div>
      </div>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="col-md-12">
        <div>
          <%= label_tag 'How would you describe your home size?' %> <br>
          <br>
          <div class="PillListy-item">
            <label>
                <input type="checkbox" name="size" id="size" value="S">
                  <span class="PillListy-label">S
                  <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                  </span>
            </label>
          </div>
        </div>
        <div>
          <div class="PillListy-item">
            <label>
                <input type="checkbox" name="size" id="size" value="M">
                  <span class="PillListy-label">M
                  <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                  </span>
            </label>
          </div>
        </div>
        <div>
          <div class="PillListy-item">
            <label>
                <input type="checkbox" name="size" id="size" value="L">
                  <span class="PillListy-label">L
                  <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                  </span>
            </label>
          </div>
        </div>
        <div>
          <div class="PillListy-item">
            <label>
                <input type="checkbox" name="size" id="size" value="XL">
                  <span class="PillListy-label">XL
                  <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                  </span>
            </label>
          </div>
        </div>
      </div>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="col-md-12">
        <div>
        <%= label_tag 'What age should your ideal animal companion be?' %> <br>
        <br>
        <div class="PillList-item">
           <label>
              <input type="checkbox" name="age" id="age" value="Teenager">
                <span class="PillList-label">Teenager
                <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                </span>
           </label>
        </div>
      </div>
      <div>
        <div class="PillList-item">
           <label>
              <input type="checkbox" name="age" id="age" value="Adult">
                <span class="PillList-label">Adult
                <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                </span>
           </label>
        </div>
      </div>
      <div>
        <div class="PillList-item">
           <label>
              <input type="checkbox" name="age" id="age" value="Elder">
                <span class="PillList-label">Elder
                <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
                </span>
           </label>
        </div>
      </div>
      </div>
    </div>
    <br>
    <br>
    <%= label_tag 'Would you be happy to remotely care for a pet?' %>
    <br>
    <fieldset class="form-group boolean optional snippet_archived">
      <div class="form-check">
        <input name="remote" type="hidden" value="true">
        <input class="form-check-input boolean optional toggle" type="checkbox" value="true" name="snippet[archived]" id="snippet_archived">
        <label class="form-check-label boolean optional" for="snippet_archived">Remote
        </label>
      </div>
    </fieldset>
    <br>
    <br>
      <div>
        <%= label_tag 'Which three traits best define you?' %>
      </div>
      <br>
    <div class="row">
      <div class="col-md-12">
        <label class="PillListb-item">
        <input type="checkbox" name="feature" value="1">
        <span class="PillListb-label">Reliable, down-to-ewarth and honest
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillList-item">
        <input type="checkbox" name="feature" value="2">
        <span class="PillList-label">Sponatneous, upbeat and fun-loving
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListy-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListy-label">Straightforward, sporty and close to nature
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
      </div>
    </div><br>
    <%= label_tag 'Which kind of movie do you like to watch?' %>
    <br>
    <div class="row">
      <div class="col-md-12">
        <label class="PillListb-item">
        <input type="checkbox" name="feature" value="1">
        <span class="PillListb-label">Madagascar
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListb-item">
        <input type="checkbox" name="feature" value="2">
        <span class="PillListb-label">American Pie
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListb-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListb-label">Into The Wild
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListb-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListb-label">Kill Bill
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListb-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListb-label">The Fabulous Destiny of Amélie Poulain
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
      </div>
    </div>

      <br>
      <div>
        <%= label_tag 'Your favourite animal is...' %>
      </div>
      <br>
    <div class="row">
      <div class="col-md-12">
        <label class="PillListy-item">
        <input type="checkbox" name="feature" value="1">
        <span class="PillListy-label">funny
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListy-item">
        <input type="checkbox" name="feature" value="2">
        <span class="PillListy-label">large and powerful
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListy-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListy-label">lively
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListy-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListy-label">tiny and convenient
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListy-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListy-label">smart
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListy-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListy-label">curious
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListy-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListy-label">cuddly
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
        <label class="PillListy-item">
        <input type="checkbox" name="feature" value="3">
        <span class="PillListy-label">relaxed
        <span class="Icon Icon--checkLight Icon--smallest"><i class="fa fa-check"></i></span>
        </span>
        </label>
      </div>
    </div><br>
    <div>
      <%= submit_tag "Submit", class:"button" %>
    </div>
    <br>
    <br>
    <% end %>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(<%=image_path("DogUp.png")%>);">
  <div class="banner-container">
    <div class="banner-flex">
      <div>
        <h1>Adopt dont shop!</h1>
        <p>There are a thousand different methods to care for a pet; discover yours! Find your perfect <br><strong> match!</strong></p>
      </div>
      <div class="wrap" >

       <%= link_to "Find your Pet match", find_animals_path, class:"button" %>
      </div>
    </div>
  </div>
</div>

<!-- middlepart-->
<div>
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%=image_path("PuppyEyes.png")%>)">
    About us
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%=image_path("fancy_cat.png")%>)">
    Our Mission
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%=image_path("cat_mystery.png")%>)">
  <%= link_to "Browse Shelters nearby", animals_path, class: "nav-link" %>
  </div>
</div>
</div>

app/views/requests/index.html.erb
<!DOCTYPE html>
<html>
  <body>
      <div class="background-2">
      <div class = "center"><i class="fa-solid fa-paw" style="font-size: 2em; color: #F2A6B0;"></i><h1>Your Requests</h1></div>
      <br>
      <br>
      <br>
        <div class = "d-flex justify-content-center">
              <ul style="list-style-type:none"><% @requests.each do |request| %>
                <li>Date: <%= request.date.strftime(" %d %b. %Y") %> <br>
                Status: <%= request.status %> <br>
                Pet: <%= request.animal.name %> <br>
                Shelter: <%= request.animal.shelter.name %>
                </li>

                <%= link_to "Send a message", request_path(request), :class => "btn btn-flat"%> <br><br>
              <% end %></ul>
        </div>
        <br>
        <br>
      </div>
    <%= link_to "Go back to homepage", root_path, :class => "btn btn-flat"%>
  </body>
</html>

app/views/requests/new.html.erb
<!DOCTYPE html>
<html>
  <body>
    <div class="background-2">
      <div class = "center"><i class="fa-solid fa-paw" style="font-size: 2em; color: #F2A6B0;"></i><h1>Tell us...</h1></div>
      <div class = "d-flex justify-content-center">
          <main>
          <div>
            <h3 class="new_h3">Your name:</h3><div class ="answer"><input type="text" name="name" placeholder = "your name"></div>
            <br>
            <h3 class="new_h3">Your email:</h3>
            <div class ="answer"><input type="text" name="email" placeholder= "your email"></div>
            <br>
            <h3 class="new_h3">Where do you live?</h3>
            <div class ="answer">
              <select name="city" id="city">
                  <option value="Munich">Munich</option>
                  <option value="Nürnburg">Nürnburg</option>
                  <option value="Würzrg">Würzburg</option>
                  <option value="Regensburg">Regensburg</option>
                  <option value="Augsburg">Augsburg</option>
                  <option value="Ingolstadt">Ingolstadt</option>
              </select>
            </div>
          </div>
          <br>
    <!-- Question 2 -->
        <div>
          <h3 class="new_h3">How long do you plan to support this pet?</h3>
          <!-- Here are the choices for the second question. Notice how each input tag has the same name (q2), but a different name than the previous question. -->
          <label><input type="radio" name="q1" value="c1">
            1 month
          </label><br />
          <label><input type="radio" name="q1" value="c2">
            3 months
          </label><br />
          <label><input type="radio" name="q1" value="c3">
            6 months
          </label><br />
          <label><input type="radio" name="q1" value="c4">
            1 year
          </label><br />
        </div>
        <br>
      <!-- Question 3 -->
        <div>
          <h3 class="new_h3">How much do you plan to support this pet?</h3>
          <p>Don't forget large dogs can eat a lot</p>
          <!-- Here are the choices for the second question. Notice how each input tag has the same name (q2), but a different name than the previous question. -->
          <label><input type="radio" name="q2" value="c1">
            20 euros per month
          </label><br />
          <label><input type="radio" name="q2" value="c2">
            30 euros per month
          </label><br />
          <label><input type="radio" name="q2" value="c3">
            40 euros per month
          </label><br />
          <label><input type="radio" name="q2" value="c4">
            55 euros per month
          </label><br />
        </div>
        <br>
        <div>
          <!-- Question 4-->
          <h3 class="new_h3">Which adopation way do you prefer?</h3>
          <!-- Choices for the third question -->
          <label><input type="radio" name="q3" value="c1">
            100% remote(only see the pet in videos)
          </label><br />
          <label><input type="radio" name="q3" value="c2">
            50% remote(visit the pet in shelter at the weekend)
          </label><br />
          <label><input type="radio" name="q3" value="c3">
            25% remote(take the pet home at the weekend)
          </label><br />
          <label><input type="radio" name="q3" value="c4">
            0% remote(I want to bring it home)
          </label><br />
        </div>
        <br>
          <div>
            <!-- Question 5-->
            <h3 class="new_h3">Is there anything else we should know?</h3>
              <label for="Description"></label>
              <div class ="description"><textarea rows="4" cols="50" name="Description"
                                  id="Description" placeholder = "Tell us more about you"></textarea></div>
          </div>
          <%# </main> %>

        <br>
        <h3 class="new_h3">When do you want to start?</h3>
              <%= simple_form_for [@animal, @request] do |f| %>
              <%= f.input :date, label: false %>
          <div style="text-align:center">
          <input type="submit" value="Confirm" class="btn btn-flat"><br>
          <br>
          <p><%= link_to "Go back to my matches",animals_path, class: "btn btn-flat" %></p>
        </div>
        <% end %>
       </main>
       </div>
    </div>
  </body>
</html>